[2024-03-26T23:37:37.956+0000] {processor.py:161} INFO - Started process (PID=16142) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:37:37.958+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:37:37.962+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:37:37.962+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:37:38.779+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:37:38.772+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:37:38.781+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:37:38.816+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.866 seconds
[2024-03-26T23:38:09.137+0000] {processor.py:161} INFO - Started process (PID=16201) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:38:09.138+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:38:09.141+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:38:09.140+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:38:09.414+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:38:09.408+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:38:09.416+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:38:09.440+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.307 seconds
[2024-03-26T23:38:39.901+0000] {processor.py:161} INFO - Started process (PID=16256) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:38:39.905+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:38:39.908+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:38:39.908+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:38:40.263+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:38:40.259+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:38:40.265+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:38:40.294+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.400 seconds
[2024-03-26T23:39:10.821+0000] {processor.py:161} INFO - Started process (PID=16313) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:39:10.823+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:39:10.825+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:39:10.825+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:39:11.091+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:39:11.084+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:39:11.094+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:39:11.127+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.312 seconds
[2024-03-26T23:39:41.511+0000] {processor.py:161} INFO - Started process (PID=16370) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:39:41.513+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:39:41.516+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:39:41.515+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:39:41.846+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:39:41.834+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:39:41.855+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:39:41.896+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.389 seconds
[2024-03-26T23:40:12.770+0000] {processor.py:161} INFO - Started process (PID=16428) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:40:12.774+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:40:12.779+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:40:12.779+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:40:13.092+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:40:13.087+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:40:13.094+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:40:13.139+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.376 seconds
[2024-03-26T23:43:12.185+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:43:12.192+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:43:12.200+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:43:12.199+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:43:12.409+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:43:12.403+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:43:12.412+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:43:12.448+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.283 seconds
[2024-03-26T23:43:43.032+0000] {processor.py:161} INFO - Started process (PID=99) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:43:43.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:43:43.040+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:43:43.040+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:43:43.209+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:43:43.199+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:43:43.212+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:43:43.240+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.214 seconds
[2024-03-26T23:44:13.899+0000] {processor.py:161} INFO - Started process (PID=156) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:44:13.901+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:44:13.905+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:44:13.904+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:44:14.025+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:44:14.021+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:44:14.027+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:44:14.067+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.175 seconds
[2024-03-26T23:44:44.533+0000] {processor.py:161} INFO - Started process (PID=213) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:44:44.535+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:44:44.538+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:44:44.538+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:44:44.668+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:44:44.663+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:44:44.670+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:44:44.701+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.173 seconds
[2024-03-26T23:45:15.630+0000] {processor.py:161} INFO - Started process (PID=270) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:45:15.639+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:45:15.644+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:45:15.644+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:45:15.916+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:45:15.901+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:45:15.922+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:45:15.966+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.343 seconds
[2024-03-26T23:45:46.360+0000] {processor.py:161} INFO - Started process (PID=327) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:45:46.361+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:45:46.364+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:45:46.364+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:45:46.498+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:45:46.489+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:45:46.502+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:45:46.531+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.177 seconds
[2024-03-26T23:46:17.514+0000] {processor.py:161} INFO - Started process (PID=384) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:46:17.517+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:46:17.603+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:46:17.602+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:46:17.820+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:46:17.809+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:46:17.822+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:46:17.851+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.343 seconds
[2024-03-26T23:46:48.161+0000] {processor.py:161} INFO - Started process (PID=441) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:46:48.163+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:46:48.165+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:46:48.165+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:46:48.402+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:46:48.399+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:46:48.404+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:46:48.430+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.273 seconds
[2024-03-26T23:47:18.749+0000] {processor.py:161} INFO - Started process (PID=498) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:47:18.751+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:47:18.754+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:47:18.754+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:47:18.862+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:47:18.857+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:47:18.863+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:47:18.887+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.143 seconds
[2024-03-26T23:47:49.026+0000] {processor.py:161} INFO - Started process (PID=555) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:47:49.028+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:47:49.033+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:47:49.031+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:47:49.139+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:47:49.135+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:47:49.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:47:49.165+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.143 seconds
[2024-03-26T23:48:19.624+0000] {processor.py:161} INFO - Started process (PID=612) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:48:19.627+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:48:19.632+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:48:19.632+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:48:20.042+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:48:20.014+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:48:20.154+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:48:20.196+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.576 seconds
[2024-03-26T23:48:50.519+0000] {processor.py:161} INFO - Started process (PID=669) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:48:50.524+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:48:50.527+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:48:50.527+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:48:50.965+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:48:50.926+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:48:50.967+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:48:50.991+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.477 seconds
[2024-03-26T23:49:21.606+0000] {processor.py:161} INFO - Started process (PID=726) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:49:21.611+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:49:21.615+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:49:21.614+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:49:22.068+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:49:22.046+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:49:22.070+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:49:22.093+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.492 seconds
[2024-03-26T23:49:52.847+0000] {processor.py:161} INFO - Started process (PID=784) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:49:52.849+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:49:52.852+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:49:52.852+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:49:53.023+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:49:53.005+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:49:53.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:49:53.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.223 seconds
[2024-03-26T23:50:23.254+0000] {processor.py:161} INFO - Started process (PID=842) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:50:23.256+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:50:23.258+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:50:23.258+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:50:23.549+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:50:23.539+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:50:23.553+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:50:23.593+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.344 seconds
[2024-03-26T23:50:53.983+0000] {processor.py:161} INFO - Started process (PID=898) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:50:53.984+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:50:53.987+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:50:53.987+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:50:54.293+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:50:54.282+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:50:54.296+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:50:54.321+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.339 seconds
[2024-03-26T23:51:24.422+0000] {processor.py:161} INFO - Started process (PID=955) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:51:24.425+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:51:24.430+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:51:24.429+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:51:24.580+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:51:24.570+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:51:24.584+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:51:24.642+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.227 seconds
[2024-03-26T23:51:55.400+0000] {processor.py:161} INFO - Started process (PID=1012) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:51:55.402+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:51:55.405+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:51:55.404+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:51:55.515+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:51:55.511+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:51:55.516+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:51:55.542+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.149 seconds
[2024-03-26T23:52:25.693+0000] {processor.py:161} INFO - Started process (PID=1069) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:52:25.695+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:52:25.698+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:52:25.697+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:52:25.914+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:52:25.907+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:52:25.929+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:52:25.970+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.282 seconds
[2024-03-26T23:52:56.394+0000] {processor.py:161} INFO - Started process (PID=1126) to work on /opt/airflow/dags/extraction.py
[2024-03-26T23:52:56.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/extraction.py for tasks to queue
[2024-03-26T23:52:56.398+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:52:56.397+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/extraction.py
[2024-03-26T23:52:56.512+0000] {logging_mixin.py:188} INFO - [2024-03-26T23:52:56.507+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/extraction.py", line 6, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'
[2024-03-26T23:52:56.516+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/extraction.py
[2024-03-26T23:52:56.550+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/extraction.py took 0.160 seconds
